<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>MyBlog.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="OpenTelemetry" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MyBlog.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyBlog.Core\MyBlog.Core.csproj" />
  </ItemGroup>
</Project>
